[package]
name = "network_recon"
version = "0.3.0"
edition = "2021"

[dependencies]
surge-ping = "0.8"
tokio = { version = "1", features = ["full"] }
futures = "0.3"
ipnet = "2.9"
trust-dns-resolver = "0.23.2" 
clap = { version = "4.4", features = ["derive"] } # for arguments